import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { SSEClientTransport } from "@modelcontextprotocol/sdk/client/sse.js";
import * as dotenv from "dotenv";

dotenv.config();

const BASE_URL = process.env.TEST_SERVER_URL || "http://localhost:3000";
const API_KEY = process.env.MCP_API_KEY || "";

async function main() {
  console.log(`[Verify] Testing MCP Server at ${BASE_URL}`);

  // 1. Verify endpoints directly
  console.log(`\n--- 1. Testing /health endpoint ---`);
  try {
    const healthRes = await fetch(`${BASE_URL}/health`);
    if (!healthRes.ok) throw new Error(`Health check failed: ${healthRes.statusText}`);
    console.log(`[OK] /health returned ${healthRes.status}`);
  } catch (err: any) {
    console.error(`[FAIL] /health endpoint failed:`, err.message);
  }

  // 2. Connect via SSE
  console.log(`\n--- 2. Connecting via SSE Transport ---`);
  
  const headers: Record<string, string> = {};
  if (API_KEY) {
    headers["Authorization"] = `Bearer ${API_KEY}`;
  }

  // Use URL object for the SSE endpoint
  const sseUrl = new URL(`${BASE_URL}/sse`);
  
  const transport = new SSEClientTransport(sseUrl, {
    requestInit: {
      headers
    }
  });

  const client = new Client(
    { name: "verify-client", version: "1.0.0" },
    { capabilities: {} }
  );

  try {
    await client.connect(transport);
    console.log(`[OK] Successfully connected to SSE endpoint.`);
  } catch (err: any) {
    console.error(`[FAIL] Could not connect via SSE:`, err.message);
    process.exit(1);
  }

  // 3. Test listTools
  console.log(`\n--- 3. Testing list_tools ---`);
  try {
    const tools = await client.listTools();
    console.log(`[OK] Found ${tools.tools.length} tools:`);
    tools.tools.forEach(t => console.log(`  - ${t.name}: ${t.description}`));
  } catch (err: any) {
    console.error(`[FAIL] listTools failed:`, err.message);
  }

  // 4. Test tool call with invalid input
  console.log(`\n--- 4. Testing invalid input handling ---`);
  try {
    await client.callTool({
      name: "gmail_send_email",
      arguments: {
        to: "not-an-array", // Invalid
        subject: "Test",
        body: "Test"
      }
    });
    console.error(`[FAIL] Expected validation error, but call succeeded.`);
  } catch (err: any) {
    console.log(`[OK] Caught expected error for invalid input: ${err.message || err.code}`);
  }

  // 5. Test gmail_create_draft (harmless write operation)
  console.log(`\n--- 5. Testing gmail_create_draft ---`);
  try {
    const draftRes = await client.callTool({
      name: "gmail_create_draft",
      arguments: {
        to: ["test-verification@example.com"],
        subject: "MCP Server Verification Draft",
        body: "This is a test draft generated by the MCP server verification script."
      }
    });
    console.log(`[OK] Draft created successfully:`, JSON.stringify(draftRes.content, null, 2));
  } catch (err: any) {
    console.error(`[FAIL] Could not create draft:`, err.message || err.code);
    console.log(`(Make sure Google OAuth is configured and tokens are valid)`);
  }

  // Close connection
  console.log(`\n--- Verification Complete ---`);
  // Workaround for some Node environments: explicitly exit since keep-alive connections might hang
  process.exit(0);
}

main().catch(console.error);
